import setuptools

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="ts_ataos",
    description="Auxiliary Telescope Active Optics System.",
    use_scm_version={
        "write_to": "python/lsst/ts/ataos/version.py",
        "write_to_template": scm_version_template,
    },
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=["bin/ataos_csc.py"],
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_ATAOS",
    },
)
