{% set data= load_setup_py_data() %}
package:
  name: ts-ataos
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - TS_CONFIG_ATTCS_DIR

test:
  requires:
    - ts-conda-build
    - astroquery
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-observatory-control
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - astroquery
    - ts-salobj
    - ts-idl
    - ts-observatory-control
