{% set data= load_setup_py_data() %}
package:
  name: ts-ataos
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_ataos_csc = lsst.ts.ataos.ataos_csc:run_ataos_csc
  script_env:
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - TS_CONFIG_ATTCS_DIR

test:
  requires:
    - ts-conda-build
    - astroquery
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-observatory-control
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - astroquery
    - ts-salobj
    - ts-idl
    - ts-observatory-control
